# Generated by Django 4.2.5 on 2023-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=50)),
                ('CourseNumber', models.IntegerField(help_text='Course Number represents the Course ID')),
            ],
        ),
    ]
