# Generated by Django 4.2.5 on 2023-09-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='CourseName',
            field=models.CharField(help_text='Cours', max_length=50),
        ),
    ]
